# Automation integration details

##############################################################################
# Computer #
############

# Steam online notification
- alias: Steam Notification
  description: 'Steam online notification'
  trigger:
  - entity_id: sensor.steam_now_playing_picture
    from: none
    platform: state
  condition: []
  action:
  - data_template:
      message: !secret steam_id_game_link
      title: Steam - Now Playing
    service: persistent_notification.create

##############################################################################
# Study #
#########

# Motion controls peripheral power when home
# Idea: Motion & device home -> power on
- alias: Power on devices control
  description: 'Motion controls peripheral device power on when home'
  mode: restart
  # Door closed
  trigger:
    - type: motion
      platform: device
      device_id: !secret motion_sensor_1_id
      entity_id: !secret motion_sensor_1_motion_entity_id
      domain: binary_sensor
      # Delay, how long the sensor needs to be active
      for:
        hours: 0
        minutes: 0
        seconds: 1
  # Phone home
  condition:
    - condition: device
      device_id: !secret my_phone_id
      domain: device_tracker
      entity_id: !secret my_phone_tracker
      type: is_home
  # Turns switch on
  action:
    - type: turn_on
      device_id: !secret power_control_1_id
      entity_id: !secret power_control_1_switch
      domain: switch

# Motion controls peripheral power off
# Idea: Trigger: Timed || device leaves home -> no motion && consumes power -> power off
- alias: Power off control
  description: 'Motion controls power off'
  mode: restart
  trigger:
    # Triggers every X minutes
    - platform: time_pattern
      minutes: "/30"
    # Phone leaves home
    - platform: device
      device_id: !secret my_phone_id
      domain: device_tracker
      entity_id: !secret my_phone_tracker
      type: leaves
      zone: zone.home
  condition:
    # Power consumption is above X Watts
    - type: is_power
      condition: device
      device_id: !secret power_control_1_id
      entity_id: !secret power_control_1_sensor
      domain: sensor
      above: 5
    # No motion verification
    - type: is_no_motion
      condition: device
      device_id: !secret motion_sensor_1_id
      entity_id: !secret motion_sensor_1_motion_entity_id
      domain: binary_sensor
      for:
        hours: 0
        minutes: 30
        seconds: 0
  action:
    # Power off from no motion
    - type: turn_off
      device_id: !secret power_control_1_id
      entity_id: !secret power_control_1_switch
      domain: switch

##############################################################################
# Kitchen #
###########

# Door open alert
# Idea: Door open & some device home -> alert notification
- alias: Door open alert
  description: 'Door controls power when home'
  mode: single
  # Door closed
  trigger:
    - type: opened            # Door state
      platform: device
      device_id: !secret door_sensor_1_id
      entity_id: !secret door_sensor_1_open_entity_id
      domain: binary_sensor
      # Delay, how long the sensor needs to be active
      for:
        hours: 0
        minutes: 1
        seconds: 0
  # Phone home
  condition:
  - condition: or
    conditions:
      - condition: device
        device_id: !secret my_phone_id
        domain: device_tracker
        entity_id: !secret my_phone_tracker
        type: is_home
      - condition: device
        device_id: !secret another_phone_id
        domain: device_tracker
        entity_id: !secret another_phone_tracker
        type: is_home
  # Notify the phone
  action:
  - device_id: !secret my_phone_id
    domain: mobile_app
    type: notify
    message: !secret door_sensor_1_open_state_msg
    title: "Home alert system"
  - device_id: !secret another_phone_id
    domain: mobile_app
    type: notify
    message: "ERROR: Door open! Close the door!"
    title: "Home assistant critical alert"
    data:
      image: "https://source.unsplash.com/random/300x200/?food"

# Motion controls coffee maker power when home
# Idea: Motion & devices home -> power on -> wait X -> notify
- alias: Power on coffee control
  description: 'Motion controls coffee maker power on when home'
  mode: single
  # Door closed
  trigger:
    - type: motion
      platform: device
      device_id: !secret motion_sensor_3_id
      entity_id: !secret motion_sensor_3_motion_entity_id
      domain: binary_sensor
      # Delay, how long the sensor needs to be active
      for:
        hours: 0
        minutes: 0
        seconds: 1
  # Phones home
  condition:
    - condition: device
      device_id: !secret my_phone_id
      domain: device_tracker
      entity_id: !secret my_phone_tracker
      type: is_home
    - condition: device
      device_id: !secret another_phone_id
      domain: device_tracker
      entity_id: !secret another_phone_tracker
      type: is_home
  # Turns switch on, waits and notifies
  action:
    - type: turn_on
      device_id: !secret power_control_3_id
      entity_id: !secret power_control_3_switch
      domain: switch
    - delay:
        hours: 0
        minutes: 3
        seconds: 0
        milliseconds: 0
    - device_id: !secret my_phone_id
      domain: mobile_app
      type: notify
      message: "Coffee ready!"
      title: "Message from the coffee maker"
      data:
        image: "https://source.unsplash.com/random/thumb/?cappuccino"
    - device_id: !secret another_phone_id
      domain: mobile_app
      type: notify
      message: "Coffee ready"
      title: "Message from the coffee maker"
      data:
        image: "https://source.unsplash.com/random/thumb/?cappuccino"

##############################################################################
# Hallway #
###########

# Water leak power control
# Idea: Leak detection turns off power
- alias: Leak power control
  description: 'Water leak control a power outlet'
  mode: single
  trigger:
    - type: moist
      platform: device
      device_id: !secret flood_sensor_2
      entity_id: !secret flood_sensor_2_detection
      domain: binary_sensor
      for:
        hours: 0
        minutes: 0
        seconds: 1
  condition: []
  action:
    - type: turn_off
      device_id: !secret power_control_2_id
      entity_id: !secret power_control_2_switch
      domain: switch
    - device_id: !secret my_phone_id
      domain: mobile_app
      type: notify
      message: "Humidifier leak detected!"
      title: "Water leak alert"
      data:
        image: "https://source.unsplash.com/random/thumb/?droplet"
    - device_id: !secret another_phone_id
      domain: mobile_app
      type: notify
      message: "Humidifier leak detected!"
      title: "Water leak alert"
      data:
        image: "https://source.unsplash.com/random/thumb/?droplet"



##############################################################################
