# Automation integration details

# Steam online notification
- alias: Steam Notification
  description: 'Steam online notification'
  trigger:
  - entity_id: sensor.steam_now_playing_picture
    from: none
    platform: state
  condition: []
  action:
  - data_template:
      message: !secret steam_id_game_link
      title: Steam - Now Playing
    service: persistent_notification.create

# Motion controls power when home
- alias: Power Control
  description: 'Motion controls power when home'
  mode: single
  # Door closed
  trigger:
    - type: motion
      platform: device
      device_id: !secret motion_sensor_id
      entity_id: !secret motion_sensor_motion_entity_id
      domain: binary_sensor
      # Delay, how long the sensor needs to be active
      for:
        hours: 0
        minutes: 0
        seconds: 1
  # Phone home
  condition:
    - condition: device
      device_id: !secret my_phone_id
      domain: device_tracker
      entity_id: !secret my_phone_tracker
      type: is_home
  # Turns switch on
  action:
    - type: turn_on
      device_id: !secret power_control_id
      entity_id: !secret power_control_switch
      domain: switch

# Door open alert
- alias: Door open alert
  description: 'Door controls power when home'
  mode: single
  # Door closed
  trigger:
    - type: opened            # Door state
      platform: device
      device_id: !secret door_sensor_id
      entity_id: !secret door_sensor_open_entity_id
      domain: binary_sensor
      # Delay, how long the sensor needs to be active
      for:
        hours: 0
        minutes: 1
        seconds: 0
  # Phone home
  condition:
  - condition: or
    conditions:
      - condition: device
        device_id: !secret my_phone_id
        domain: device_tracker
        entity_id: !secret my_phone_tracker
        type: is_home
      - condition: device
        device_id: !secret another_phone_id
        domain: device_tracker
        entity_id: !secret another_phone_tracker
        type: is_home
  # Notify the phone
  action:
  - device_id: !secret my_phone_id
    domain: mobile_app
    type: notify
    message: !secret door_sensor_open_state_msg
    title: "Home alert system"
  - device_id: !secret another_phone_id
    domain: mobile_app
    type: notify
    message: "ERROR: Door open! Close the door!"
    title: "Home assistant critical alert"
    data:
      image: https://source.unsplash.com/random/300x200/?food

