# Home Assistant main configurations

# Initialization settings
homeassistant:
  name: !secret home_name
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  currency: !secret currency
  time_zone: !secret time_zone
  internal_url: !secret internal_url
  #external_url: "https://www.example.com"

# Default configurations
# Do not remove!
default_config:

# Integrations
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml

# Text to speech
tts:
  - platform: google_translate

# IFTTT
ifttt:
  key: !secret ifttt_api_key

# Z-wave server reload
rest_command:
  reload_zwavejs:
    url: !secret reload_zwave_url
    method: POST
    headers:
      authorization: !secret reload_zwave_token
      content-type: application/json
