# Home Assistant main configurations

##############################################################################
# General configurations

# Initialization settings
homeassistant:
  name: !secret home_name
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  currency: !secret currency
  time_zone: !secret time_zone
  internal_url: !secret internal_url
  #external_url: "https://www.example.com"
  customize: !include customize.yaml

  # Default configurations
  # Do not remove!
  default_config:

  # Text to speech
  tts:
    - platform: google_translate
