# Custom integrations

# Includes from other files
automation: !include automations.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml

# Z-wave server reload
rest_command:
  reload_zwavejs:
    url: !secret reload_zwave_url
    method: POST
    headers:
      authorization: !secret reload_zwave_token
      content-type: application/json
