# Raspberry Pi sensors
- platform: command_line
  name: "CPU temperature"
  unit_of_measurement: '°C'
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  value_template: '{{ value | multiply(0.001) | round(2) }}'

# Steam
- platform: steam_online
  api_key: !secret steam_api_key
  accounts:
    - !secret steam_id

# Current Steam game  
- platform: template
  sensors:
    steam_game:
      friendly_name: "Now Playing"
      value_template: !secret steam_id_game
    steam_now_playing_picture:
      friendly_name: "Now Playing Game Picture"
      value_template: !secret steam_id_game_img
