version: '3'
services:
  zjs:
    container_name: zjs
    image: kpine/zwave-js-server:${ZWAVE_SERVER_IMAGE_VERSION}
    restart: unless-stopped
    stop_signal: SIGINT
    environment:
      S2_ACCESS_CONTROL_KEY: ${S2_ACCESS_CONTROL_KEY}
      S2_AUTHENTICATED_KEY: ${S2_AUTHENTICATED_KEY}
      S2_UNAUTHENTICATED_KEY: ${S2_UNAUTHENTICATED_KEY}
      S0_LEGACY_KEY: ${S0_LEGACY_KEY}
    volumes:
      - ${HOME}/ha-cache:/cache
    devices:
      - '/dev/ttyACM0:/dev/zwave'
    ports:
      - '8091:8091'     # Web interface
      - '3000:3000'     # zwave-js websocket server

  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:${HA_IMAGE_VERSION}
    restart: unless-stopped
    privileged: true
    volumes:
      - ${HOME}/ha:/config
      - /etc/localtime:/etc/localtime:ro
    network_mode: host
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    healthcheck:
      test: ["CMD", "curl", "-s", "http://127.0.0.1:8123"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 30s
