version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: home-assistant/home-assistant:${HA_IMAGE_VERSION}
    restart: unless-stopped
    privileged: true
    volumes:
      - ${HOME}/ha:/config
      - /etc/localtime:/etc/localtime:ro
    network_mode: host
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    depends_on:
      - "zjs"

  zjs:
    container_name: zjs
    image: kpine/zwave-js-server:${ZWAVE_SERVER_IMAGE_VERSION}
    restart: unless-stopped
    environment:
      S2_ACCESS_CONTROL_KEY: ${S2_ACCESS_CONTROL_KEY}
      S2_AUTHENTICATED_KEY: ${S2_AUTHENTICATED_KEY}
      S2_UNAUTHENTICATED_KEY: ${S2_UNAUTHENTICATED_KEY}
      S0_LEGACY_KEY: ${S0_LEGACY_KEY}
    volumes:
      - ${HOME}/ha-cache:/cache
    devices:
      - '/dev/ttyACM0:/dev/zwave'
    ports:
      - '3000:3000'
