version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "home-assistant/home-assistant:2022.7.3@sha256:cdd625f5b9edd3d5413705357405373b065dd4925ba316f8d0bc68d73fae6463"
    volumes:
      - ${HOME}/ha:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    devices:
      - /dev/ttyACM0:/dev/ttyACM0

  zjs:
    container_name: zjs
    image: kpine/zwave-js-server:1.20.0-9.6.0@sha256:ed2089ecd266fa6c631212399bebb3da29649c5c0eaf67b0409b801e99c62352
    restart: unless-stopped
    environment:
      S2_ACCESS_CONTROL_KEY: "7764841BC794A54442E324682A550CEF"
      S2_AUTHENTICATED_KEY: "66EA86F088FFD6D7497E0B32BC0C8B99"
      S2_UNAUTHENTICATED_KEY: "2FAB1A27E19AE9C7CC6D18ACEB90C357"
      S0_LEGACY_KEY: "17DFB0C1BED4CABFF54E4B5375E257B3"
    devices:
      - '/dev/ttyACM0:/dev/zwave'
    volumes:
      - ${HOME}/ha-cache:/cache
    ports:
      - '3000:3000'
